version: '3'

services:

  mariadb:
    container_name: moodle-mariadb
    image:  mariadb:10.9.2
    ports:
      - 3306:3306
    volumes:
      - ./.data/mariadb:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_moodle
    networks:
      - moodle-net      

  moodle:
    container_name: moodle-host
    image: bitnami/moodle:4.1.1
    ports:
      - 8080:8080
    volumes:
      - ./.data/moodle:/bitnami/moodle
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - MOODLE_DATABASE_NAME=bitnami_moodle
    depends_on:
      - mariadb
    networks:
      - moodle-net

networks:
  moodle-net:
    driver: bridge

# docker run -d --name mariadb \
#   --env ALLOW_EMPTY_PASSWORD=yes \
#   --env MARIADB_USER=bn_moodle \
#   --env MARIADB_PASSWORD=bitnami \
#   --env MARIADB_DATABASE=bitnami_moodle \
#   --network moodle-network \
#   --volume mariadb_data:/bitnami/mariadb \
#   bitnami/mariadb:latest

# $ docker volume create --name moodle_data
# docker run -d --name moodle \
#   -p 8080:8080 -p 8443:8443 \
#   --env ALLOW_EMPTY_PASSWORD=yes \
#   --env MOODLE_DATABASE_USER=bn_moodle \
#   --env MOODLE_DATABASE_PASSWORD=bitnami \
#   --env MOODLE_DATABASE_NAME=bitnami_moodle \
#   --network moodle-network \
#   --volume moodle_data:/bitnami/moodle \
#   bitnami/moodle:latest
